version: 2
updates:

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    reviewers:
      - "istankovic"
      - "palango"

  # - package-ecosystem: "npm"
  #   directory: "/frontend/"
  #   schedule:
  #     interval: "weekly"
  #     day: "thursday"
  #   reviewers:
  #     - "nekhaly"
  #     - "manuelwedler"
