project_structure:
    build: contracts/build
    contracts: contracts/contracts
    interfaces: contracts/interfaces
    reports: contracts/reports
    scripts: contracts/scripts
    tests: contracts/tests

dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.4.2

compiler:
  evm_version: london
  solc:
    version: 0.8.12

dev_deployment_artifacts: true

networks:
  development:
    cmd_settings:
      chain_id: 1337
