project_structure:
    build: contracts/build
    contracts: contracts/contracts
    interfaces: contracts/interfaces
    reports: contracts/reports
    tests: contracts/tests

dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.8.0

compiler:
  evm_version: london
  solc:
    version: 0.8.13

dev_deployment_artifacts: true
