FROM python:3.9

COPY . /src
WORKDIR /src
RUN mkdir -p ./beamer/data/relayers
RUN mv ./relayer/relayer-node16-*-x64 ./beamer/data/relayers/
RUN pip install poetry
RUN poetry install --no-dev --no-interaction --no-ansi -vvv

ENTRYPOINT ["poetry", "run", "beamer-agent"]
