FROM python:3.10

COPY README.md pyproject.toml poetry.lock /src/
COPY beamer /src/beamer

RUN mkdir -p /src/beamer/data/relayers
COPY ./relayer/relayer-node16-*-x64 /src/beamer/data/relayers/

WORKDIR /src
RUN pip install poetry
RUN poetry install --no-dev --no-interaction --no-ansi -vvv

LABEL org.opencontainers.image.licenses "MIT"
LABEL org.opencontainers.image.source "https://github.com/beamer-bridge/beamer"
LABEL org.opencontainers.image.description "An agent that can be used to participate in the Beamer bridge protocol."

ENTRYPOINT ["poetry", "run", "beamer-agent"]
