name: Raisync CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    env:
      DOCKER_BUILDKIT: 1
      COMPOSE_DOCKER_CLI_BUILD: 1

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - uses: actions/setup-python@v2.3.2
        with:
          python-version: 3.9

      - name: Cache ~/.local
        uses: actions/cache@v2
        with:
          path: ~/.local
          key: dotlocal-${{ runner.os }}-${{ hashFiles('.github/workflows/ci.yml', 'poetry.lock') }}

      - uses: Gr1N/setup-poetry@v7

      - name: Cache Python packages
        id: cache-python-packages
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/pypoetry/virtualenvs
            ~/.solcx
          key: poetry-1-${{ runner.os }}-${{ hashFiles('.github/workflows/ci.yml', 'poetry.lock') }}

      - name: Install ganache
        run: npm install ganache-cli --global

      - name: Install dependencies
        run: poetry install
        if: steps.cache-python-packages.outputs.cache-hit != 'true'

      - name: Cache brownie packages
        id: cache-brownie-packages
        uses: actions/cache@v2
        with:
          path: ~/.brownie/packages
          key: ${{ runner.os }}-brownie-${{ hashFiles('brownie-config.yaml') }}

      - name: Install brownie contract libraries
        if: steps.cache-brownie-packages.outputs.cache-hit != 'true'
        run: |
          poetry run brownie pm install OpenZeppelin/openzeppelin-contracts@4.4.2

      - name: Lint contracts
        run: |
          poetry run black --check contracts
          poetry run flake8 contracts

      - name: Lint raisync
        run: |
          poetry run black --check raisync scripts
          poetry run flake8 raisync
          poetry run mypy raisync

      - name: Run contract tests
        run: |
          poetry run brownie test -v -G

      - name: Run node tests
        run: |
          # Generate deployment artifacts under contracts/build/deployments/dev.
          # Start ganache separately so that brownie does not need to start
          # it. If brownie starts ganache, it will remove the generated
          # deployment artifacts after it is done.
          ganache-cli --accounts 10 --hardfork istanbul --gasLimit 12000000 --mnemonic brownie --port 8545 -q &
          pushd contracts && poetry run brownie run deploy && popd
          killall node

          poetry run brownie test raisync/tests -v -G --cov raisync --cov-report=term

      - name: Bring the stack up
        working-directory: docker/optimism/ops
        run: |
          ./scripts/stats.sh &
          docker-compose -f docker-compose.yml -f docker-compose-nobuild.yml up --scale relayer=1 -d

      - name: Wait for the Sequencer node
        working-directory: docker/optimism/ops
        run: ./scripts/wait-for-sequencer.sh

      - name: Run E2E tests
        run: sh ./docker/optimism.sh e2e
