name: Build beamer-agent container image

on:
  push:
    branches:
      - 'main'
    tags:
      - 'v*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: beamer-bridge/beamer-agent

jobs:
  prepare-package:
    uses: ./.github/workflows/prepare-package.yml

  build-and-push-image:
    runs-on: ubuntu-latest
    needs: prepare-package
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'false'

      - uses: actions/download-artifact@v3
        with:
          name: relayers
          path: relayer/

      - name: Log in to the Container registry
        uses: docker/login-action@v2.0.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate container metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=sha,format=long
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
          flavor: latest=true

      - name: Build and push container image
        uses: docker/build-push-action@v3.1.0
        with:
          context: .
          file: docker/Dockerfile.agent
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
