# This is meant to be used only as a reusable workflow.
name: Prepare for packaging

on:
    workflow_call:

jobs:
  prepare-for-packaging:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3.1.0
        with:
          submodules: 'false'

      - uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Prepare relayers
        run: make relayers

      - uses: actions/upload-artifact@v3
        with:
          name: relayers
          path: relayer/relayer-node16-*
          retention-days: 1
